//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Zupree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public int ProductId { get; set; }
        public int PaymentId { get; set; }
        public int Quantity { get; set; }
        public decimal SalesUnitPrice { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Product Product { get; set; }
    }
}
